#!/usr/bin/env bash
SCRIPTDIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
# shellcheck source-path=SCRIPTDIR
source "$SCRIPTDIR/../strict-mode.bash"

# shellcheck disable=SC2154 # This is what we’re testing.
echo "$undefined"
