#!/usr/bin/env bash
SCRIPTDIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
# shellcheck source-path=SCRIPTDIR
source "$SCRIPTDIR/../strict-mode.bash"

RESULT=$(cat nothing-here-man)
echo "$RESULT"
