name: 'illustrate check_suite trigger'

on:
  check_suite:
    types: ['completed']

jobs:
  report:
    # NB: This checks that `latest_check_runs_count` is at least the number of
    #     runs we have, because garnix ends up triggering this workflow twice –
    #     once after evaluation and a second time after building all the
    #     derivations. The first time will have fewer (but often not exactly
    #     one) completed checks, so we use that to only have the job run once
    #     per check_suite completion.
    if: ${{ github.event.check_suite.app.name == 'Garnix CI'
            && github.event.check_suite.conclusion == 'success'
            && github.event.check_suite.latest_check_runs_count >= 16 }}
    name: 'The suite is finished'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'report completion'
        run: |
          echo "check_suite completed!"
